name: Setup Pre-Deploy Environment
on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  setup-preview:
    runs-on: ubuntu-latest
    if: ${{ inputs.environment == 'preview' }}
    steps:
      - uses: actions/checkout@v2
      - name: Copy/Overwrite robots.txt with development robots.txt
        run: cp -v public/dev/robots.txt public/robots.txt
      - name: Copy/Overwrite sitemap.xml with development sitemap.xml
        run: cp -v public/dev/sitemap.xml public/sitemap.xml
      - name: Check copy was successful
        run: if [ -f public/robots.txt ] && [ -f public/sitemap.xml ]; then echo "Files copied successfully"; else exit 1; fi
      - name: Complete Development Environment Setup
        uses: mscoutermarsh/cowsays-action@master
        with:
          text: "Development environment setup complete"
          color: "green"
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Automated changes
          commit_options: "--no-verify"
          commit_user_name: "github-actions[bot]"
          commit_user_email: "github-actions[bot]@users.noreply.github.com"
          file_pattern: "public/*"
          status_options: '--untracked-files=no'
      - name: "Run if changes have been detected"
        if: steps.auto-commit-action.outputs.changes_detected == 'true'
        run: echo "Changes!"

      - name: "Run if no changes have been detected"
        if: steps.auto-commit-action.outputs.changes_detected == 'false'
        run: echo "No Changes!"


  setup-production:
    runs-on: ubuntu-latest
    if: ${{ inputs.environment == 'production' }}
    steps:
      - uses: actions/checkout@v2
      - name: Copy/Overwrite robots.txt with production robots.txt
        run: cp -v public/prod/robots.txt public/robots.txt
      - name: Copy/Overwrite sitemap.xml with production sitemap.xml
        run: cp -v public/prod/sitemap.xml public/sitemap.xml
      - name: Check copy was successful
        run: if [ -f public/robots.txt ] && [ -f public/sitemap.xml ]; then echo "Files copied successfully"; else exit 1; fi
      - name: Complete Production Environment Setup
        uses: mscoutermarsh/cowsays-action@master
        with:
          text: "Production environment setup complete"
          color: "green"
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Automated changes
          commit_options: "--no-verify"
          commit_user_name: "github-actions[bot]"
          commit_user_email: "github-actions[bot]@users.noreply.github.com"
          file_pattern: "public/*"
          status_options: '--untracked-files=no'
      - name: "Run if changes have been detected"
        if: steps.auto-commit-action.outputs.changes_detected == 'true'
        run: echo "Changes!"

      - name: "Run if no changes have been detected"
        if: steps.auto-commit-action.outputs.changes_detected == 'false'
        run: echo "No Changes!"
