name: Setup Pre-Deploy Environment
on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  setup-preview:
    runs-on: ubuntu-latest
    if: ${{ inputs.environment == 'preview' }}
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Copy/Overwrite robots.txt with development robots.txt
        run: cp -v public/dev/robots.txt public/robots.txt
      - name: Copy/Overwrite sitemap.xml with development sitemap.xml
        run: cp -v public/dev/sitemap.xml public/sitemap.xml
      - name: Check copy was successful
        run: if [ -f public/robots.txt ] && [ -f public/sitemap.xml ]; then echo "Files copied successfully"; else exit 1; fi
      - name: Complete Development Environment Setup
        uses: mscoutermarsh/cowsays-action@master
        with:
          text: "Development environment setup complete"
          color: "green"
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          message: Automated changes
          add: 'public/*'
      - name: "Run if changes have been detected"
        if: steps.add-and-commit.outputs.pushed == 'true'
        run: echo "Changes pushed!"
      - name: "Run if no changes have been detected"
        if: steps.add-and-commit.outputs.pushed == 'false'
        run: echo "No Changes!"


  setup-production:
    runs-on: ubuntu-latest
    if: ${{ inputs.environment == 'production' }}
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Copy/Overwrite robots.txt with production robots.txt
        run: cp -v public/prod/robots.txt public/robots.txt
      - name: Copy/Overwrite sitemap.xml with production sitemap.xml
        run: cp -v public/prod/sitemap.xml public/sitemap.xml
      - name: Check copy was successful
        run: if [ -f public/robots.txt ] && [ -f public/sitemap.xml ]; then echo "Files copied successfully"; else exit 1; fi
      - name: Complete Production Environment Setup
        uses: mscoutermarsh/cowsays-action@master
        with:
          text: "Production environment setup complete"
          color: "green"
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          message: Automated changes
          add: 'public/*'
      - name: "Run if changes have been detected"
        if: steps.add-and-commit.outputs.pushed == 'true'
        run: echo "Changes pushed!"
      - name: "Run if no changes have been detected"
        if: steps.add-and-commit.outputs.pushed == 'false'
        run: echo "No Changes!"